apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- configmap.yaml

namespace: flask-app-prod

namePrefix: prod-

patches:
- path: patches/deployment-patch.yaml
- path: patches/service-patch.yaml

images:
- name: ghcr.io/mfarajpour/flask-gitops-app
  newTag: v3.0.0

labels:
- pairs:
    environment: production
    tier: production
