apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- namespace.yaml
- configmap.yaml

namespace: flask-app-staging

namePrefix: staging-

patches:
- path: patches/deployment-patch.yaml
- path: patches/service-patch.yaml

images:
- name: ghcr.io/mfarajpour/flask-gitops-app
  newTag: v1.6.0-rc.1

labels:
- pairs:
    environment: staging
    tier: staging
